# Generated by Django 5.2.9 on 2026-01-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='FaceCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='Faces',
            field=models.JSONField(blank=True, help_text='List of user  detected in this photo  [{userid, username}]', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
