# Generated by Django 5.2.9 on 2026-01-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_photo_facecount_photo_faces_photo_isprocessed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewedphoto',
            unique_together=set(),
        ),
    ]
