"""
Django settings for KeepEvents project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# CORE DJANGO SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1tw^7jzh%%0r1lo6$tkf&6^s%esu42a2tq7b4-n(9*lgz$o0x3"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Hosts/domain names that are valid for this site
ALLOWED_HOSTS = []


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [

      "daphne",
    # Django built-in apps
    "django.contrib.sites",           # Required for allauth - manages multiple sites
    "django.contrib.auth",            # Authentication framework
    "django.contrib.contenttypes",    # Content type system
    "django.contrib.sessions",        # Session framework
    "django.contrib.messages",        # Messaging framework
    "django.contrib.staticfiles",     # Static file management
    "django.contrib.admin",           # Admin interface

    # Django REST Framework
    "rest_framework",                 # API framework

    # Django Allauth - Social authentication
    "allauth",                        # Core allauth app
    "allauth.account",                # Account management (login, signup, etc.)
    "allauth.socialaccount",          # Social account connections
    "allauth.socialaccount.providers.google",  # Google OAuth provider

  
    # Custom project apps
    "events",                         # Event management app
    "photos",                         # Photo management app
    "users.apps.UsersConfig",         # Custom user model and user management
    "guardian",                       # Object-level permissions
    "api",                            # API endpoints

    # CORS Headers
    "corsheaders",                    # Cross-Origin Resource Sharing support

    #celery 
    "django_celery_results",

    #sockets
    "channels",
    "realtime",
]

# ==============================================================================
# CELERY CONFIG
# ==============================================================================

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"

# ==============================================================================
# Web Sockets CONFIG
# ==============================================================================

ASGI_APPLICATION = "KeepEvents.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# ==============================================================================
# MIDDLEWARE CONFIGURATION
# ==============================================================================
# Middleware is processed in order for requests (top to bottom)
# and in reverse for responses (bottom to top)

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",               # CORS header handling
    "django.middleware.security.SecurityMiddleware",        # Security enhancements
    "django.contrib.sessions.middleware.SessionMiddleware", # Session management
    "django.middleware.common.CommonMiddleware",            # Common utilities (URL rewriting, etc.)
    "django.middleware.csrf.CsrfViewMiddleware",           # CSRF protection
    "allauth.account.middleware.AccountMiddleware",         # Allauth account handling
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # Associates users with requests
    "django.contrib.messages.middleware.MessageMiddleware", # Message framework
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Clickjacking protection
    
]


# ==============================================================================
# URL CONFIGURATION
# ==============================================================================

# Root URL configuration module
ROOT_URLCONF = "KeepEvents.urls"


# ==============================================================================
# TEMPLATE CONFIGURATION
# ==============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],                    # Additional directories to search for templates
        "APP_DIRS": True,              # Look for templates in each app's templates/ directory
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",  # Makes request available in templates
                "django.contrib.auth.context_processors.auth", # Adds user and perms to context
                "django.contrib.messages.context_processors.messages",  # Adds messages to context
            ],
        },
    },
]


# ==============================================================================
# WSGI CONFIGURATION
# ==============================================================================

# WSGI application used by Django's runserver
WSGI_APPLICATION = "KeepEvents.wsgi.application"


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "autumndjango",
        "USER": "autumndbuser",
        "PASSWORD": "strongpassword",
        "HOST": "localhost",
        "PORT": "5432",
    }
}



# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================
# Validators that check password strength

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},  # Prevents passwords similar to user info
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},            # Enforces minimum length
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},           # Prevents common passwords
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},          # Prevents numeric-only passwords
]


# ==============================================================================
# AUTHENTICATION BACKENDS
# ==============================================================================
# Order matters - Django tries each backend in sequence

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",      # Standard Django authentication
    "guardian.backends.ObjectPermissionBackend",      # Object-level permissions via Guardian
)


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = "en-us"  # Default language
TIME_ZONE = "UTC"        # Default timezone
USE_I18N = True          # Enable Django's translation system
USE_TZ = True            # Enable timezone-aware datetimes


# ==============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# ==============================================================================

STATIC_URL = "/static/"                # URL prefix for static files
STATIC_ROOT = BASE_DIR / "staticfiles" # Where collectstatic will collect files for production
STATICFILES_DIRS = [
    BASE_DIR / "static",               # Additional locations for static files
]


# ==============================================================================
# MEDIA FILES (User-uploaded content)
# ==============================================================================

MEDIA_URL = "/media/"        # URL prefix for media files
MEDIA_ROOT = BASE_DIR / "media"  # Filesystem path where media files are stored


# ==============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ==============================================================================

from datetime import timedelta


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.authentication.CookieJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

#===============================================================================
# SIMPLE_JWT 
#===============================================================================

SIMPLE_JWT = {
     "USER_ID_FIELD": "userid",     
    "USER_ID_CLAIM": "user_id",

    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=55),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = False


# SESSION_COOKIE_SECURE = False      # True in production (HTTPS)
CSRF_COOKIE_SECURE = False         # True in production

# SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_HTTPONLY = False

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]


# ==============================================================================
# CUSTOM USER MODEL
# ==============================================================================

# Points to custom user model instead of Django's default
AUTH_USER_MODEL = "users.users"


# ==============================================================================
# DJANGO GUARDIAN CONFIGURATION
# ==============================================================================

# Username for anonymous users in Guardian permission system
ANONYMOUS_USER_NAME = "Anonymous"


# ==============================================================================
# DJANGO ALLAUTH CONFIGURATION
# ==============================================================================

SITE_ID = 1  # ID of the current site in django.contrib.sites

# Email verification settings
ACCOUNT_EMAIL_VERIFICATION = "none"   # Disabled - will handle our own OTP verification
ACCOUNT_AUTHENTICATION_METHOD = "email"  # Use email instead of username for login
ACCOUNT_EMAIL_REQUIRED = True  # Email is required for registration

# New allauth configuration (replaces deprecated settings)
ACCOUNT_LOGIN_METHODS = {'email'}  # Users log in with email
ACCOUNT_SIGNUP_FIELDS = {
    'email': {'required': True},
    'username': {'required': True},
    'password1': {'required': True},
    'password2': {'required': True},
}

# Social account provider configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": "<YOUR_GOOGLE_CLIENT_ID>",     # Google OAuth client ID
            "secret": "<YOUR_GOOGLE_CLIENT_SECRET>",    # Google OAuth client secret
            "key": "",
        },
        "SCOPE": ["profile", "email"],  # Permissions requested from Google
        "AUTH_PARAMS": {"access_type": "online"},  # OAuth parameters
    }
}


# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # For development - prints to console
# DEFAULT_FROM_EMAIL = "no-reply@keepevents.local"

# Production email settings using Gmail SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # Gmail SMTP server
EMAIL_PORT = 587               # TLS port
EMAIL_USE_TLS = True           # Use TLS encryption

# Load sensitive email credentials from config file
import json
with open( "../config.json") as f:
    config = json.load(f)

EMAIL_HOST_USER = config["EMAIL_HOST_USER"]         # Gmail address
EMAIL_HOST_PASSWORD = config["EMAIL_HOST_PASSWORD"] # Gmail app password
DEFAULT_FROM_EMAIL = "your_email@gmail.com"


# ==============================================================================
# OMNIPORT CONFIGURATION (Custom OAuth)
# ==============================================================================

OMNIPORT_CLIENT_ID = config["CLIENT_ID"]           # Omniport OAuth client ID
OMNIPORT_CLIENT_SECRET = config["CLIENT_SECRET"]   # Omniport OAuth client secret
OMNIPORT_BASE_URL = config["BASE_URL"]             # Omniport API base URL
OMNIPORT_REDIRECT_URI = config["REDIRECT_URI"]     # OAuth redirect URI


# ==============================================================================
# CORS (Cross-Origin Resource Sharing) CONFIGURATION
# ==============================================================================

CORS_ALLOW_ALL_ORIGINS = True  # Allow requests from any origin (development only!)
CORS_ALLOW_CREDENTIALS = True  # Allow cookies to be sent with requests

# Allowed HTTP headers in CORS requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',      # Required for token authentication
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',       # Required for CSRF protection
    'x-requested-with',
]

FRONTEND_URL = "http://localhost:5173"

#c==========================

#       caching 

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
